
baseURL = "https://example.com/"
title = "Гипнотерапия 2.0"
languageCode = "ru"
# disable rss etc for now
disableKinds = ["taxonomy", "taxonomyTerm", "RSS", "sitemap", "robotsTXT"]
# Available Hugo themes (uncomment one to use):
# theme = "PaperMod"
# theme = "LoveIt"
# theme = "BeautifulHugo"
# theme = "toha"
# theme = "jane"
# theme = "introduction"
# theme = "hyde"
# theme = "hermit-v2"
theme = "KeepIt"
# theme = "up-business-theme"
# theme = "hugoplate"
# theme = "long-teng"

[params]
  highlightcss = ""
  disablePico = true

[menu]
  [[menu.main]]
    name = "Главная"
    url  = "/"
    weight = 1
  [[menu.main]]
    name = "Обо мне"
    url  = "/about/"
    weight = 2
  [[menu.main]]
    name = "Услуги"
    url  = "/services/"
    weight = 3
  [[menu.main]]
    name = "FAQ"
    url  = "/faq/"
    weight = 4
  [[menu.main]]
    name = "Контакты"
    url  = "/contact/"
    weight = 5
