baseURL = "https://drkristof.com/"
title = "Dr. Sebastian Kristof"
languageCode = "ru"
# disable rss etc for now
disableKinds = ["taxonomy", "taxonomyTerm", "RSS", "sitemap", "robotsTXT"]
# Available Hugo themes (uncomment one to use):
theme = "PaperMod"
# theme = "LoveIt"
# theme = "BeautifulHugo"
# theme = "toha"
# theme = "jane"
# theme = "introduction"
# theme = "hyde"
# theme = "hermit-v2"
# theme = "KeepIt"
# theme = "up-business-theme"
# theme = "hugoplate"
# theme = "long-teng"

[params]
  highlightcss = ""
  disablePico = true
  # website title for Open Graph and Twitter Cards
  title = "Dr. Sebastian Kristof"
  # website description for RSS, SEO, Open Graph and Twitter Cards
  description = "Deep subconscious reprogramming by Dr. Sebastian Kristof"
  # website images for Open Graph and Twitter Cards
  images = []

[menu]
  [[menu.main]]
    name = "Личная терапия"
    url  = "/"
    weight = 1
  [[menu.main]]
    name = "Аудио-программы"
    url  = "/audio/"
    weight = 2
  [[menu.main]]
    name = "Приложения"
    url  = "/apps/"
    weight = 3
  [[menu.main]]
    name = "О гипнотерапии"
    url  = "/about-hypnosis/"
    weight = 4
  [[menu.main]]
    name = "Блог"
    url  = "/blog/"
    weight = 5
