baseURL: "https://example.com/"
title: "Гипнотерапия 2.0"
languageCode: "ru"
defaultContentLanguage: "ru"
pagination:
  pagerSize: 10   # how many page links Hugo shows in the pager
  # path: page    # optional: change /page/1/ → /str/1/ etc.
  # disableAliases: false   # optional: keep /page/1/ alias pages

disableKinds:        # “taxonomyterm” is now just “taxonomy”
  - taxonomy
  - RSS
  - sitemap
  - robotsTXT   # keep if you don’t want /robots.txt

module:
  imports:
    - path: github.com/hugo-toha/toha/v4   # pulls the theme as a Hugo Module

menus:
  - identifier: home
    name: "Главная"
    url: "/"
    weight: 1
  - identifier: about
    name: "Обо мне"
    url: "/about/"
    weight: 2
  - identifier: services
    name: "Услуги"
    url: "/services/"
    weight: 3
  - identifier: faq
    name: "FAQ"
    url: "/faq/"
    weight: 4
  - identifier: contact
    name: "Контакты"
    url: "/contact/"
    weight: 5
